// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getZone(args: GetZoneArgs, opts?: pulumi.InvokeOptions): Promise<GetZoneResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("powerdns:index/getZone:getZone", {
        "id": args.id,
        "serverId": args.serverId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getZone.
 */
export interface GetZoneArgs {
    id: string;
    serverId: string;
}

/**
 * A collection of values returned by getZone.
 */
export interface GetZoneResult {
    readonly id: string;
    readonly kind: string;
    readonly name: string;
    readonly serverId: string;
}
export function getZoneOutput(args: GetZoneOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetZoneResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("powerdns:index/getZone:getZone", {
        "id": args.id,
        "serverId": args.serverId,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getZone.
 */
export interface GetZoneOutputArgs {
    id: pulumi.Input<string>;
    serverId: pulumi.Input<string>;
}
