// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { GetRecordsetArgs, GetRecordsetResult, GetRecordsetOutputArgs } from "./getRecordset";
export const getRecordset: typeof import("./getRecordset").getRecordset = null as any;
export const getRecordsetOutput: typeof import("./getRecordset").getRecordsetOutput = null as any;
utilities.lazyLoad(exports, ["getRecordset","getRecordsetOutput"], () => require("./getRecordset"));

export { GetZoneArgs, GetZoneResult, GetZoneOutputArgs } from "./getZone";
export const getZone: typeof import("./getZone").getZone = null as any;
export const getZoneOutput: typeof import("./getZone").getZoneOutput = null as any;
utilities.lazyLoad(exports, ["getZone","getZoneOutput"], () => require("./getZone"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));

export { RecordsetArgs, RecordsetState } from "./recordset";
export type Recordset = import("./recordset").Recordset;
export const Recordset: typeof import("./recordset").Recordset = null as any;
utilities.lazyLoad(exports, ["Recordset"], () => require("./recordset"));

export { ZoneArgs, ZoneState } from "./zone";
export type Zone = import("./zone").Zone;
export const Zone: typeof import("./zone").Zone = null as any;
utilities.lazyLoad(exports, ["Zone"], () => require("./zone"));


// Export sub-modules:
import * as config from "./config";

export {
    config,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "powerdns:index/recordset:Recordset":
                return new Recordset(name, <any>undefined, { urn })
            case "powerdns:index/zone:Zone":
                return new Zone(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("powerdns", "index/recordset", _module)
pulumi.runtime.registerResourceModule("powerdns", "index/zone", _module)
pulumi.runtime.registerResourcePackage("powerdns", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:powerdns") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
