// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The provider type for the powerdns package. By default, resources use package-wide configuration
 * settings, however an explicit `Provider` instance may be created and passed during resource
 * construction to achieve fine-grained programmatic control over provider settings. See the
 * [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
 */
export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'powerdns';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === "pulumi:providers:" + Provider.__pulumiType;
    }

    /**
     * REST API authentication key
     */
    public readonly apiKey!: pulumi.Output<string>;
    /**
     * Content or path of a Root CA to be used to verify PowerDNS's SSL certificate
     */
    public readonly caCertificate!: pulumi.Output<string | undefined>;
    /**
     * Set cache memory size in MB
     */
    public readonly cacheMemSize!: pulumi.Output<string | undefined>;
    /**
     * Location of PowerDNS server
     */
    public readonly serverUrl!: pulumi.Output<string>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            if ((!args || args.apiKey === undefined) && !opts.urn) {
                throw new Error("Missing required property 'apiKey'");
            }
            if ((!args || args.serverUrl === undefined) && !opts.urn) {
                throw new Error("Missing required property 'serverUrl'");
            }
            resourceInputs["apiKey"] = args ? args.apiKey : undefined;
            resourceInputs["caCertificate"] = args ? args.caCertificate : undefined;
            resourceInputs["cacheMemSize"] = args ? args.cacheMemSize : undefined;
            resourceInputs["cacheRequests"] = pulumi.output(args ? args.cacheRequests : undefined).apply(JSON.stringify);
            resourceInputs["cacheTtl"] = pulumi.output(args ? args.cacheTtl : undefined).apply(JSON.stringify);
            resourceInputs["insecureHttps"] = pulumi.output(args ? args.insecureHttps : undefined).apply(JSON.stringify);
            resourceInputs["serverUrl"] = args ? args.serverUrl : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Provider.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * REST API authentication key
     */
    apiKey: pulumi.Input<string>;
    /**
     * Content or path of a Root CA to be used to verify PowerDNS's SSL certificate
     */
    caCertificate?: pulumi.Input<string>;
    /**
     * Set cache memory size in MB
     */
    cacheMemSize?: pulumi.Input<string>;
    /**
     * Enable cache REST API requests
     */
    cacheRequests?: pulumi.Input<boolean>;
    /**
     * Set cache TTL in seconds
     */
    cacheTtl?: pulumi.Input<number>;
    /**
     * Disable verification of the PowerDNS server's TLS certificate
     */
    insecureHttps?: pulumi.Input<boolean>;
    /**
     * Location of PowerDNS server
     */
    serverUrl: pulumi.Input<string>;
}
