// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Recordset extends pulumi.CustomResource {
    /**
     * Get an existing Recordset resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RecordsetState, opts?: pulumi.CustomResourceOptions): Recordset {
        return new Recordset(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'powerdns:index/recordset:Recordset';

    /**
     * Returns true if the given object is an instance of Recordset.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Recordset {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Recordset.__pulumiType;
    }

    /**
     * Name for record set (e.g. "www.powerdns.com.")
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * All records in this record set.
     */
    declare public readonly records: pulumi.Output<string[]>;
    /**
     * The id of the server.
     */
    declare public readonly serverId: pulumi.Output<string>;
    /**
     * DNS TTL of the records, in seconds.
     */
    declare public readonly ttl: pulumi.Output<number>;
    /**
     * Type of this record (e.g. "A", "PTR", "MX").
     */
    declare public readonly type: pulumi.Output<string>;
    /**
     * ID of the zone this record set belongs to.
     */
    declare public readonly zoneId: pulumi.Output<string>;

    /**
     * Create a Recordset resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RecordsetArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RecordsetArgs | RecordsetState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RecordsetState | undefined;
            resourceInputs["name"] = state?.name;
            resourceInputs["records"] = state?.records;
            resourceInputs["serverId"] = state?.serverId;
            resourceInputs["ttl"] = state?.ttl;
            resourceInputs["type"] = state?.type;
            resourceInputs["zoneId"] = state?.zoneId;
        } else {
            const args = argsOrState as RecordsetArgs | undefined;
            if (args?.records === undefined && !opts.urn) {
                throw new Error("Missing required property 'records'");
            }
            if (args?.serverId === undefined && !opts.urn) {
                throw new Error("Missing required property 'serverId'");
            }
            if (args?.ttl === undefined && !opts.urn) {
                throw new Error("Missing required property 'ttl'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            if (args?.zoneId === undefined && !opts.urn) {
                throw new Error("Missing required property 'zoneId'");
            }
            resourceInputs["name"] = args?.name;
            resourceInputs["records"] = args?.records;
            resourceInputs["serverId"] = args?.serverId;
            resourceInputs["ttl"] = args?.ttl;
            resourceInputs["type"] = args?.type;
            resourceInputs["zoneId"] = args?.zoneId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Recordset.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Recordset resources.
 */
export interface RecordsetState {
    /**
     * Name for record set (e.g. "www.powerdns.com.")
     */
    name?: pulumi.Input<string>;
    /**
     * All records in this record set.
     */
    records?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The id of the server.
     */
    serverId?: pulumi.Input<string>;
    /**
     * DNS TTL of the records, in seconds.
     */
    ttl?: pulumi.Input<number>;
    /**
     * Type of this record (e.g. "A", "PTR", "MX").
     */
    type?: pulumi.Input<string>;
    /**
     * ID of the zone this record set belongs to.
     */
    zoneId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Recordset resource.
 */
export interface RecordsetArgs {
    /**
     * Name for record set (e.g. "www.powerdns.com.")
     */
    name?: pulumi.Input<string>;
    /**
     * All records in this record set.
     */
    records: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The id of the server.
     */
    serverId: pulumi.Input<string>;
    /**
     * DNS TTL of the records, in seconds.
     */
    ttl: pulumi.Input<number>;
    /**
     * Type of this record (e.g. "A", "PTR", "MX").
     */
    type: pulumi.Input<string>;
    /**
     * ID of the zone this record set belongs to.
     */
    zoneId: pulumi.Input<string>;
}
