valkey:
  enabled: true
  architecture: standalone
  auth:
    existingSecret: 'grist-env'
    existingSecretPasswordKey: 'REDIS_PASSWORD'
  master:
    persistence:
      enabled: true
      storageClass: 'kadalu.pool'
      accessMode: 'ReadWriteOnce'
      size: '2Gi'
    affinity:
      podAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: 'app.kubernetes.io/name'
                    operator: 'In'
                    values:
                      - 'grist'
              topologyKey: 'kubernetes.io/hostname'
