// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("desec");

/**
 * The API token for operations.
 */
export declare const apiToken: string | undefined;
Object.defineProperty(exports, "apiToken", {
    get() {
        return __config.get("apiToken");
    },
    enumerable: true,
});

export declare const apiUri: string | undefined;
Object.defineProperty(exports, "apiUri", {
    get() {
        return __config.get("apiUri");
    },
    enumerable: true,
});

/**
 * The max number of retries when sending an API request.
 */
export declare const retryMax: number | undefined;
Object.defineProperty(exports, "retryMax", {
    get() {
        return __config.getObject<number>("retryMax");
    },
    enumerable: true,
});

