// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Domain extends pulumi.CustomResource {
    /**
     * Get an existing Domain resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DomainState, opts?: pulumi.CustomResourceOptions): Domain {
        return new Domain(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'desec:index/domain:Domain';

    /**
     * Returns true if the given object is an instance of Domain.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Domain {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Domain.__pulumiType;
    }

    declare public /*out*/ readonly created: pulumi.Output<string>;
    declare public readonly domainId: pulumi.Output<string>;
    declare public /*out*/ readonly keys: pulumi.Output<outputs.DomainKey[]>;
    declare public /*out*/ readonly minimumTtl: pulumi.Output<number>;
    declare public readonly name: pulumi.Output<string>;
    declare public /*out*/ readonly published: pulumi.Output<string>;

    /**
     * Create a Domain resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: DomainArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DomainArgs | DomainState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DomainState | undefined;
            resourceInputs["created"] = state?.created;
            resourceInputs["domainId"] = state?.domainId;
            resourceInputs["keys"] = state?.keys;
            resourceInputs["minimumTtl"] = state?.minimumTtl;
            resourceInputs["name"] = state?.name;
            resourceInputs["published"] = state?.published;
        } else {
            const args = argsOrState as DomainArgs | undefined;
            resourceInputs["domainId"] = args?.domainId;
            resourceInputs["name"] = args?.name;
            resourceInputs["created"] = undefined /*out*/;
            resourceInputs["keys"] = undefined /*out*/;
            resourceInputs["minimumTtl"] = undefined /*out*/;
            resourceInputs["published"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Domain.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Domain resources.
 */
export interface DomainState {
    created?: pulumi.Input<string>;
    domainId?: pulumi.Input<string>;
    keys?: pulumi.Input<pulumi.Input<inputs.DomainKey>[]>;
    minimumTtl?: pulumi.Input<number>;
    name?: pulumi.Input<string>;
    published?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Domain resource.
 */
export interface DomainArgs {
    domainId?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
}
