// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Rrset extends pulumi.CustomResource {
    /**
     * Get an existing Rrset resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RrsetState, opts?: pulumi.CustomResourceOptions): Rrset {
        return new Rrset(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'desec:index/rrset:Rrset';

    /**
     * Returns true if the given object is an instance of Rrset.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Rrset {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Rrset.__pulumiType;
    }

    public /*out*/ readonly created!: pulumi.Output<string>;
    public readonly domain!: pulumi.Output<string>;
    public /*out*/ readonly name!: pulumi.Output<string>;
    public readonly records!: pulumi.Output<string[]>;
    public readonly rrsetId!: pulumi.Output<string>;
    public readonly subname!: pulumi.Output<string>;
    public readonly ttl!: pulumi.Output<number>;
    public readonly type!: pulumi.Output<string>;

    /**
     * Create a Rrset resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RrsetArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RrsetArgs | RrsetState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RrsetState | undefined;
            resourceInputs["created"] = state ? state.created : undefined;
            resourceInputs["domain"] = state ? state.domain : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["records"] = state ? state.records : undefined;
            resourceInputs["rrsetId"] = state ? state.rrsetId : undefined;
            resourceInputs["subname"] = state ? state.subname : undefined;
            resourceInputs["ttl"] = state ? state.ttl : undefined;
            resourceInputs["type"] = state ? state.type : undefined;
        } else {
            const args = argsOrState as RrsetArgs | undefined;
            if ((!args || args.domain === undefined) && !opts.urn) {
                throw new Error("Missing required property 'domain'");
            }
            if ((!args || args.records === undefined) && !opts.urn) {
                throw new Error("Missing required property 'records'");
            }
            if ((!args || args.subname === undefined) && !opts.urn) {
                throw new Error("Missing required property 'subname'");
            }
            if ((!args || args.ttl === undefined) && !opts.urn) {
                throw new Error("Missing required property 'ttl'");
            }
            if ((!args || args.type === undefined) && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["domain"] = args ? args.domain : undefined;
            resourceInputs["records"] = args ? args.records : undefined;
            resourceInputs["rrsetId"] = args ? args.rrsetId : undefined;
            resourceInputs["subname"] = args ? args.subname : undefined;
            resourceInputs["ttl"] = args ? args.ttl : undefined;
            resourceInputs["type"] = args ? args.type : undefined;
            resourceInputs["created"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Rrset.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Rrset resources.
 */
export interface RrsetState {
    created?: pulumi.Input<string>;
    domain?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    records?: pulumi.Input<pulumi.Input<string>[]>;
    rrsetId?: pulumi.Input<string>;
    subname?: pulumi.Input<string>;
    ttl?: pulumi.Input<number>;
    type?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Rrset resource.
 */
export interface RrsetArgs {
    domain: pulumi.Input<string>;
    records: pulumi.Input<pulumi.Input<string>[]>;
    rrsetId?: pulumi.Input<string>;
    subname: pulumi.Input<string>;
    ttl: pulumi.Input<number>;
    type: pulumi.Input<string>;
}
