// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class TokenPolicy extends pulumi.CustomResource {
    /**
     * Get an existing TokenPolicy resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TokenPolicyState, opts?: pulumi.CustomResourceOptions): TokenPolicy {
        return new TokenPolicy(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'desec:index/tokenPolicy:TokenPolicy';

    /**
     * Returns true if the given object is an instance of TokenPolicy.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TokenPolicy {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TokenPolicy.__pulumiType;
    }

    declare public readonly domain: pulumi.Output<string | undefined>;
    declare public readonly permWrite: pulumi.Output<boolean>;
    declare public readonly subname: pulumi.Output<string | undefined>;
    declare public readonly tokenId: pulumi.Output<string>;
    declare public readonly tokenPolicyId: pulumi.Output<string>;
    declare public readonly type: pulumi.Output<string | undefined>;

    /**
     * Create a TokenPolicy resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TokenPolicyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TokenPolicyArgs | TokenPolicyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TokenPolicyState | undefined;
            resourceInputs["domain"] = state?.domain;
            resourceInputs["permWrite"] = state?.permWrite;
            resourceInputs["subname"] = state?.subname;
            resourceInputs["tokenId"] = state?.tokenId;
            resourceInputs["tokenPolicyId"] = state?.tokenPolicyId;
            resourceInputs["type"] = state?.type;
        } else {
            const args = argsOrState as TokenPolicyArgs | undefined;
            if (args?.permWrite === undefined && !opts.urn) {
                throw new Error("Missing required property 'permWrite'");
            }
            if (args?.tokenId === undefined && !opts.urn) {
                throw new Error("Missing required property 'tokenId'");
            }
            resourceInputs["domain"] = args?.domain;
            resourceInputs["permWrite"] = args?.permWrite;
            resourceInputs["subname"] = args?.subname;
            resourceInputs["tokenId"] = args?.tokenId;
            resourceInputs["tokenPolicyId"] = args?.tokenPolicyId;
            resourceInputs["type"] = args?.type;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(TokenPolicy.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering TokenPolicy resources.
 */
export interface TokenPolicyState {
    domain?: pulumi.Input<string>;
    permWrite?: pulumi.Input<boolean>;
    subname?: pulumi.Input<string>;
    tokenId?: pulumi.Input<string>;
    tokenPolicyId?: pulumi.Input<string>;
    type?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a TokenPolicy resource.
 */
export interface TokenPolicyArgs {
    domain?: pulumi.Input<string>;
    permWrite: pulumi.Input<boolean>;
    subname?: pulumi.Input<string>;
    tokenId: pulumi.Input<string>;
    tokenPolicyId?: pulumi.Input<string>;
    type?: pulumi.Input<string>;
}
