// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Token extends pulumi.CustomResource {
    /**
     * Get an existing Token resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TokenState, opts?: pulumi.CustomResourceOptions): Token {
        return new Token(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'desec:index/token:Token';

    /**
     * Returns true if the given object is an instance of Token.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Token {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Token.__pulumiType;
    }

    public readonly allowedSubnets!: pulumi.Output<string[]>;
    public readonly autoPolicy!: pulumi.Output<boolean>;
    public /*out*/ readonly created!: pulumi.Output<string>;
    public readonly name!: pulumi.Output<string>;
    public /*out*/ readonly owner!: pulumi.Output<string>;
    public readonly permCreateDomain!: pulumi.Output<boolean>;
    public readonly permDeleteDomain!: pulumi.Output<boolean>;
    public readonly permManageTokens!: pulumi.Output<boolean>;
    public /*out*/ readonly token!: pulumi.Output<string>;
    public readonly tokenId!: pulumi.Output<string>;

    /**
     * Create a Token resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: TokenArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TokenArgs | TokenState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TokenState | undefined;
            resourceInputs["allowedSubnets"] = state ? state.allowedSubnets : undefined;
            resourceInputs["autoPolicy"] = state ? state.autoPolicy : undefined;
            resourceInputs["created"] = state ? state.created : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["owner"] = state ? state.owner : undefined;
            resourceInputs["permCreateDomain"] = state ? state.permCreateDomain : undefined;
            resourceInputs["permDeleteDomain"] = state ? state.permDeleteDomain : undefined;
            resourceInputs["permManageTokens"] = state ? state.permManageTokens : undefined;
            resourceInputs["token"] = state ? state.token : undefined;
            resourceInputs["tokenId"] = state ? state.tokenId : undefined;
        } else {
            const args = argsOrState as TokenArgs | undefined;
            resourceInputs["allowedSubnets"] = args ? args.allowedSubnets : undefined;
            resourceInputs["autoPolicy"] = args ? args.autoPolicy : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["permCreateDomain"] = args ? args.permCreateDomain : undefined;
            resourceInputs["permDeleteDomain"] = args ? args.permDeleteDomain : undefined;
            resourceInputs["permManageTokens"] = args ? args.permManageTokens : undefined;
            resourceInputs["tokenId"] = args ? args.tokenId : undefined;
            resourceInputs["created"] = undefined /*out*/;
            resourceInputs["owner"] = undefined /*out*/;
            resourceInputs["token"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Token.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Token resources.
 */
export interface TokenState {
    allowedSubnets?: pulumi.Input<pulumi.Input<string>[]>;
    autoPolicy?: pulumi.Input<boolean>;
    created?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    owner?: pulumi.Input<string>;
    permCreateDomain?: pulumi.Input<boolean>;
    permDeleteDomain?: pulumi.Input<boolean>;
    permManageTokens?: pulumi.Input<boolean>;
    token?: pulumi.Input<string>;
    tokenId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Token resource.
 */
export interface TokenArgs {
    allowedSubnets?: pulumi.Input<pulumi.Input<string>[]>;
    autoPolicy?: pulumi.Input<boolean>;
    name?: pulumi.Input<string>;
    permCreateDomain?: pulumi.Input<boolean>;
    permDeleteDomain?: pulumi.Input<boolean>;
    permManageTokens?: pulumi.Input<boolean>;
    tokenId?: pulumi.Input<string>;
}
