// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface DomainKey {
    dnskey: pulumi.Input<string>;
    ds: pulumi.Input<pulumi.Input<string>[]>;
    flags: pulumi.Input<number>;
    keytype: pulumi.Input<string>;
}
